# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
