# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('confirmation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txID', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
