# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_products_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inStock',
        ),
        migrations.AddField(
            model_name='products',
            name='couponCode',
            field=models.CharField(default=b'0000000', max_length=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
