# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160705_1034'),
        ('hello', '0002_paymentrequest_transaction'),
    ]

    operations = [
    ]
