# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_paymentrequest_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='confirmation',
            field=models.CharField(default='False', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='address2',
            field=models.CharField(default='What is this', max_length=60),
            preserve_default=False,
        ),
    ]
