# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160819_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sellerId',
            field=models.CharField(default='NONE', max_length=60),
            preserve_default=False,
        ),
    ]
