# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_products_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='confirmations',
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmations',
            field=models.IntegerField(default=0),
        ),
    ]
