# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_paymentrequest_cartjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='sessionToken',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
