# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20160819_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(default='UNPAID', max_length=60),
            preserve_default=False,
        ),
    ]
